version = 1

exclude_patterns = [
  "target/**",
  "**/*.rs.bk",
  "Cargo.lock"
]

test_patterns = [
  "tests/**",
  "**/*_test.rs",
  "**/test_*.rs"
]

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "stable"
  skip_doc_coverage = ["module"]

[[transformers]]
name = "rustfmt"
enabled = true